on: [push]

jobs:
  soos_dast_baseline_analysis:
    name: SOOS DAST Baseline Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@feature/PA-11731 # GET Latest Version from https://github.com/marketplace/actions/soos-dast
        with:

          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: 'GH-Actions-DAST-wait-for-password'
          auth_form_type: 'wait_for_password'
          target_url: 'https://demoqa.com/profile'
          api_url: 'https://qa-api.soos.io/api/'          
          auth_login_url: 'https://demoqa.com/login'                  
          auth_username: 'franco'        
          auth_password: 'Password1!'        
          auth_username_field: 'username'        
          auth_password_field:           
          auth_submit_field: 'login'
          on_failure: 'continue_on_failure'
